spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: "/static/**"
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:ecommerce
      driverClassName: org.h2.Driver
      username: sa
      password:
      hikari:
        maximum-pool-size: 150
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
